### ISSUE TITLE
You need a license

### ISSUE THREAD

**Issue by BookOwl** [Cosmic-Search/Universe#3]
Even I know what you are trying to do, if you don't have any license at all legally it is the same thing as having it copyrighted. The [Unlicense](http://unlicense.org/) sounds like what you want.

**Comment by CosmicWebServices** [comment]
https://choosealicense.com/no-license/ <= This is what we are using

**Comment by BookOwl** [comment]
Did you read that page?
It says

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software

and 

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

So unless you include some license, your project is still copyrighted and non-free.

**Comment by BookOwl** [comment]
As I said before, the unlicense sounds like what you are trying to do.
